//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoteHomePrism.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RemoteHomePrism.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://169.254.80.80:3333/api/Audio/.
        /// </summary>
        internal static string AudioBaseUri {
            get {
                return ResourceManager.GetString("AudioBaseUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string PageAboutTitle {
            get {
                return ResourceManager.GetString("PageAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select song.
        /// </summary>
        internal static string PageAudioChoseAudio {
            get {
                return ResourceManager.GetString("PageAudioChoseAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string PageAudioPause {
            get {
                return ResourceManager.GetString("PageAudioPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string PageAudioPlay {
            get {
                return ResourceManager.GetString("PageAudioPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        internal static string PageAudioPower {
            get {
                return ResourceManager.GetString("PageAudioPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string PageAudioStop {
            get {
                return ResourceManager.GetString("PageAudioStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        internal static string PageAudioTitle {
            get {
                return ResourceManager.GetString("PageAudioTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string PageHomeTitle {
            get {
                return ResourceManager.GetString("PageHomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lighting.
        /// </summary>
        internal static string PageLightingTitle {
            get {
                return ResourceManager.GetString("PageLightingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string PageMenuTitle {
            get {
                return ResourceManager.GetString("PageMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        internal static string PageSecurityTitle {
            get {
                return ResourceManager.GetString("PageSecurityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shades.
        /// </summary>
        internal static string PageShadesTitle {
            get {
                return ResourceManager.GetString("PageShadesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        internal static string PageTemperatureTitle {
            get {
                return ResourceManager.GetString("PageTemperatureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current program.
        /// </summary>
        internal static string PageWashMachineCurrentProgram {
            get {
                return ResourceManager.GetString("PageWashMachineCurrentProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        internal static string PageWashMachinePower {
            get {
                return ResourceManager.GetString("PageWashMachinePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        internal static string PageWashMachineProgress {
            get {
                return ResourceManager.GetString("PageWashMachineProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string PageWashMachineStart {
            get {
                return ResourceManager.GetString("PageWashMachineStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wash Machine.
        /// </summary>
        internal static string PageWashMachineTitle {
            get {
                return ResourceManager.GetString("PageWashMachineTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water pomp.
        /// </summary>
        internal static string PageWaterPompTitle {
            get {
                return ResourceManager.GetString("PageWaterPompTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://169.254.80.80:3333/api/WashMachine/.
        /// </summary>
        internal static string WashMachineBaseUri {
            get {
                return ResourceManager.GetString("WashMachineBaseUri", resourceCulture);
            }
        }
    }
}
